#!/usr/bin/env python3

import json
import os
import sys

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

TF_OUTPUT = os.path.join(BASE_DIR, "..", "tf-output.json")

INVENTORY_FILE = os.path.join(
    BASE_DIR,
    "..",
    "inventories",
    "production",
    "hosts.ini"
)


def load_outputs():

    if not os.path.exists(TF_OUTPUT):

        print("\nERROR: tf-output.json not found\n")

        print("Run:\n")

        print("terraform output -json > tf-output.json\n")

        sys.exit(1)

    with open(TF_OUTPUT) as f:
        data = json.load(f)

    return data.get("outputs", data)


def get_value(outputs, key):

    if key not in outputs:

        print(f"\nERROR: Missing Terraform output: {key}\n")

        sys.exit(1)

    value = outputs[key]

    if isinstance(value, dict):

        return value.get("value")

    return value


def main():

    print("\nGenerating Ansible inventory...\n")

    outputs = load_outputs()

    master_ip = get_value(outputs, "master_public_ip")

    worker1_ip = get_value(outputs, "worker_node_1_public_ip")

    worker2_ip = get_value(outputs, "worker_node_2_public_ip")

    kubectl_ip = get_value(outputs, "Proxy_server_ip")


    content = f"""# Auto-generated by generate_inventory.py
# Do not edit manually

[master]
{master_ip}

[workers]
{worker1_ip}
{worker2_ip}

[kubectl]
{kubectl_ip}
"""


    os.makedirs(os.path.dirname(INVENTORY_FILE), exist_ok=True)

    with open(INVENTORY_FILE, "w") as f:

        f.write(content)


    print("Inventory successfully generated:\n")

    print("Master:", master_ip)

    print("Worker1:", worker1_ip)

    print("Worker2:", worker2_ip)

    print("Kubectl:", kubectl_ip)

    print("\nLocation:")

    print(INVENTORY_FILE)

    print("")


if __name__ == "__main__":

    main()