---
# create .kube directory for ubuntu user
- name: Ensure .kube directory exists
  ansible.builtin.file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

# fetch admin.conf from master and write it locally
- name: Slurp admin.conf from master node
  ansible.builtin.slurp:
    src: /etc/kubernetes/admin.conf
  delegate_to: "{{ groups['master'][0] }}"
  register: admin_conf
  run_once: true

- name: Write kubeconfig file on kubectl host
  ansible.builtin.copy:
    content: "{{ admin_conf.content | b64decode }}"
    dest: /home/ubuntu/.kube/config
    owner: ubuntu
    group: ubuntu
    mode: '0600'
