---

# Install NGINX Ingress Controller
# Uses kubeconfig explicitly to avoid localhost:8080 errors

- name: Check if ingress-nginx namespace exists
  command: kubectl get namespace ingress-nginx --kubeconfig=/etc/kubernetes/admin.conf
  register: ingress_check
  failed_when: false
  changed_when: false


- name: Install NGINX Ingress Controller
  command: >
    kubectl apply
    -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.3.0/deploy/static/provider/cloud/deploy.yaml
    --kubeconfig=/etc/kubernetes/admin.conf
  when: ingress_check.rc != 0